### Task 1 - Data Collection
Here you will obtain the required data for the analysis. As described in the project instructions, you will perform a web scrap to obtain data from the NCDC website, import data from the John Hopkins repository, and import the provided external data.

### A - NCDC Website scrap
Website - https://covid19.ncdc.gov.ng/

In [21]:
import requests
import numpy as np
import urllib.request
import pandas as pd
import csv
from bs4 import BeautifulSoup
import seaborn as sns
sns.set_style("darkgrid")
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('fivethirtyeight')  
import warnings
warnings.filterwarnings('ignore')

In [22]:
r = requests.get('https://covid19.ncdc.gov.ng')
soup = BeautifulSoup(r.text,'lxml')
soup

<!DOCTYPE html>
<html lang="en">
<head><meta content="text/html;charset=utf-8" http-equiv="content-type"/>
<title>NCDC Coronavirus COVID-19 Microsite</title>
<!--[if lt IE 11]>
    	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    	<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    	<![endif]-->
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui" name="viewport"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="" name="description"/>
<meta content="" name="keywords"/>
<meta content="Codedthemes" name="author"/>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-PLDLB6N');</script>
<link href="/static/img/index.ico" rel="icon" type="image/x-icon"/>
<link href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css" rel="stylesheet" type="text/css"/>
<link href="https://cdn.jsdelivr.net/npm/line-awesome@1.3.0/dist/line-awesome/css/line-awesome.min.css" rel="stylesheet" type="text/css"/>
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" type="text/css"/>
<link href="/static/css/style.css " rel="stylesheet"/>
<link href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css" rel="stylesheet" type="text/css"/>
<style>
        html,
        body {
          margin: 0;
          height: 100%;
          width: 100%;

          box-sizing: border-box;
        }

        #travel{
      width: 600px;
        }

        @media only screen and (max-device-width: 480px) {
          #travel{
      width: 350px;
        }

      }
      </style>
<link href="https://ncdcgloepid.blob.core.windows.net/ncdc-gloepid/gloepid-embed.min.css" rel="stylesheet"/>
</head><body class="">
<div class="loader-bg">
<div class="loader-track">
<div class="loader-fill"></div>
</div>
</div>
<style>
  .pcoded-header.header-green a:hover, .pcoded-header.header-green dropdown-toggle {
    color:#FFC82D;
}
</style>
<nav class="pcoded-navbar menupos-fixed menu-light">
<div class="navbar-wrapper">
<div class="navbar-content scroll-div">
<ul class="nav pcoded-inner-navbar">
<li class="nav-item pcoded-menu-caption">
<label>NAVIGATION</label>
</li>
<li class="nav-item">
<a class="nav-link" href="/report/"> <span class="pcoded-micon"><i class="feather icon-home"></i></span><span class="pcoded-mtext">Dashboard</span></a>
</li>
<li class="nav-item">
<a class="nav-link" href="/state/"><span class="pcoded-micon"><i class="fas fa-chart-bar"></i></span><span class="pcoded-mtext">Epicurve</span></a>
</li>
<li class="nav-item">
<a class="nav-link" href="/progression/"><span class="pcoded-micon"><i class="feather icon-layout"></i></span><span class="pcoded-mtext">Progression</span></a>
</li>
<li class="nav-item">
<a class="nav-link" href="/faq/"><span class="pcoded-micon"><i class="feather icon-users"></i></span><span class="pcoded-mtext">FAQs</span></a>
</li>
<li class="nav-item">
<a class="nav-link" href="/nitpfaq/"><span class="pcoded-micon"><i class="fa fa-plane"></i></span><span class="pcoded-mtext">Travel Portal FAQs</span></a>
</li>
<li class="nav-item">
<a class="nav-link" href="/advisory/"><span class="pcoded-micon"><i class="feather icon-gitlab"></i></span><span class="pcoded-mtext">Advisory</span></a>
</li>
<li class="nav-item">
<a class="nav-link" href="/guideline/"><span class="pcoded-micon"><i class="fa fa-book"></i></span><span class="pcoded-mtext">Guidelines</span></a>
</li>
<li class="nav-item">
<a class="nav-link" href="/samplesites/"><span class="pcoded-micon"><i class="feather icon-feather"></i></span><span class="pcoded-mtext">Sample Collection Sites</span></a>
</li>
<li class="nav-item">
<a class="nav-link" href="/resource/"><span class="pcoded-micon"><i class="feather icon-feather"></i></span><span class="pcoded-mtext">Resources</span></a>
</li>
<li class="nav-item pcoded-hasmenu">
<a class="nav-link" href="#!"><span class="pcoded-micon"><i class="fa fa-flask"></i></span><span class="pcoded-mtext">Laboratories</span></a>
<ul class="pcoded-submenu">
<li><a href="/laboratory/">Government Laboratories</a></li>
<li><a href="/privatelabs/">Fee-Paying Private Laboratories</a></li>
<li><a href="/corporatelabs/">Corporate Labs</a></li>
</ul>
</li>
<li class="nav-item pcoded-hasmenu">
<a class="nav-link" href="#!"><span class="pcoded-micon"><i class="feather icon-home"></i></span><span class="pcoded-mtext">Nigeria Data</span></a>
<ul class="pcoded-submenu">
<li><a href="/gis/">Web View</a></li>
<li><a href="/gism/">Mobile View</a></li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link" href="/globals/"><span class="pcoded-micon"><i class="feather icon-layers"></i></span><span class="pcoded-mtext">Global</span></a>
</li>
<div class="card text-center">
<div class="card-block">
<button aria-hidden="true" class="close" data-dismiss="alert" type="button">Ã—</button>
<i class="fa fa-users-o f-40"></i>
<h6 class="mt-3">Self Assessment</h6>
<p>
<a class="btn btn-success btn-sm text-white m-0" href="https://selfassessment.ncdc.gov.ng" target="_blank">Get Your COVID-19 Risk Assessment</a>
</p>
</div>
</div>
</ul>
</div>
</div>
</nav>
<header class="navbar pcoded-header navbar-expand-lg navbar-light headerpos-fixed header-green">
<div class="m-header">
<a class="mobile-menu" href="#!" id="mobile-collapse"><span></span></a>
<a class="b-brand" href="#!">
<img alt="" class="logo" height="45" src="/static/ncdc_img/ncdc_logo_black_text.png" width="120"/>
</a>
<a class="mob-toggler" href="#!">
<i class="feather icon-more-vertical"></i>
</a>
</div>
<div class="collapse navbar-collapse">
<ul class="navbar-nav mr-auto">
<li class="nav-item">
</li>
<li class="nav-item">
<a class="full-screen" href="#!" onclick="javascript:toggleFullScreen()"><i class="feather icon-maximize"></i></a>
</li>
</ul>
<ul class="navbar-nav ml-auto">
<li>
<div class="dropdown">
<a href="https://ngcovid19resourcetracker.info" target="_blank"><i class="fa fa-blog"></i> <span>PTF Resource</span></a>
</div>
</li>
<li>
<div class="dropdown">
<a href="/validation/"><i class="fa fa-check"></i> <span>Check Test Results</span></a>
</div>
</li>
<li>
<div class="dropdown">
<a href="/contact/"><i class="fa fa-phone"></i> <span>State Emergency Contacts</span></a>
</div>
</li>
<li>
<div class="dropdown">
<a href="https://ncdc.gov.ng/diseases/sitreps/?cat=14&amp;name=An%20update%20of%20COVID-19%20outbreak%20in%20Nigeria" target="_blank"><i class="fa fa-newspaper"></i> <span>Situation Reports</span></a>
</div>
</li>
<li>
<div class="dropdown">
<a href="https://covid19blog.ncdc.gov.ng/" target="_blank"><i class="fa fa-blog"></i> <span>COVID19blog</span></a>
</div>
</li>
<li>
<div class="dropdown">
<a href="https://ncdc.gov.ng/" target="_blank"><i class="fa fa-rocket"></i>
<span>NCDC</span></a>
</div>
</li>
<li>
</li>
</ul>
</div>
</header>
<div class="pcoded-main-container">
<div class="pcoded-content">
<div class="page-header">
<div class="page-block">
<div class="row">
<div class="col-md-12 col-xl-9">
<div class="card bg-c-white order-card">
<div class="card-body">
<h1 class="text-black">COVID-19 NIGERIA </h1>
<h6></h6><p class="m-b-0"><span class="float-right">
<script>

                                            var months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
                                            var days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

                                            var d = new Date();
                                          var day = days[d.getDay()];
                                          var hr = d.getHours();
                                            var min = d.getMinutes();
                                        if (min < 10) {
                                            min = "0" + min;
                                            }
                                            var ampm = "am";
                                            if( hr > 12 ) {
                                              hr -= 12;
                                              ampm = "pm";
                                            }
                                    var date = d.getDate();
                                    var month = months[d.getMonth()];
                                    var year = d.getFullYear();
                                    var x = document.getElementById("time");
                                    var fullDate = day + " " + hr + ":" + min + " "+ ampm + " " + date + " " + month + " " + year;
                                    document.write(fullDate);
                                        </script>
</span></p>
</div>
</div>
</div>
<style>.newcol {
                            background: rgba(106, 98, 36, 0.64);
                        }
                        </style>
<div class="col-md-12 col-xl-3">
<div class="card newcol order-card">
<div class="card-body">
<h6 class="text-white">Samples Tested</h6>
<h2 class="text-right text-white">
<i class="fa fa-viruses float-left"></i><span>5,441,162</span></h2>
</div>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-xs-3 col-md-3 col-xl-3">
<div class="card bg-c-blue order-card">
<div class="card-body">
<h6 class="text-white">Confirmed Cases</h6>
<h2 class="text-right text-white"><i class="fa fa-viruses float-left"></i><span>263,322</span></h2>
</div>
</div>
</div>
<div class="col-xs-3 col-md-3 col-xl-3">
<div class="card bg-c-yellow order-card">
<div class="card-body">
<h6 class="text-white">Active Cases</h6>
<h2 class="text-right text-white"><i class="fa fa-viruses float-left"></i><span>2,921</span></h2>
</div>
</div>
</div>
<div class="col-xs-3 col-md-3 col-xl-3">
<div class="card bg-c-green order-card">
<div class="card-body">
<h6 class="text-white">Discharged Cases</h6>
<h2 class="text-right text-white"><i class="fa fa-viruses float-left"></i><span>257,253</span></h2>
</div>
</div>
</div>
<div class="col-xs-3 col-md-3 col-xl-3">
<div class="card bg-c-red order-card">
<div class="card-body">
<h6 class="text-white">Death</h6>
<h2 class="text-right text-white"><i class="fa fa-viruses float-left"></i><span>3,148</span></h2>
</div>
</div>
</div>
<style>
                    #custom1 {
                        border-collapse: collapse;
                        width: 100%;
                        /*font-family: Segoe;*/
                    }

                    #custom1 td, #custom1 th {
                        border: 1px solid #ddd;
                        padding: 8px;
                    }

                    #custom1 tr:nth-child(even) {
                        background-color: #f2f2f2;
                    }

                    #custom1 tr:hover {
                        background-color: #ddd;
                    }

                    #custom1 th {
                        padding-top: 12px;
                        padding-bottom: 12px;
                        text-align: left;
                        background-color: #138750;
                        color: white;
                    }
                </style>
</div>
<div class="row">
<div class="col-xl-7">
<div class="card">
<div class="card-header">
<h4 class="card-title">Confirmed Cases by State</h4>
</div>
<div class="card-body">
<div class="table-responsive">
<table id="custom1">
<thead>
<tr>
<th>States Affected</th>
<th>No. of Cases (Lab Confirmed)</th>
<th>No. of Cases (on admission)</th>
<th>No. Discharged</th>
<th>No. of Deaths</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Lagos
</td>
<td>103,145
</td>
<td>2
</td>
<td>102,372
</td>
<td>771
</td>
</tr>
<tr>
<td>
FCT
</td>
<td>29,161
</td>
<td>120
</td>
<td>28,792
</td>
<td>249
</td>
</tr>
<tr>
<td>
Rivers
</td>
<td>17,755
</td>
<td>180
</td>
<td>17,420
</td>
<td>155
</td>
</tr>
<tr>
<td>
Kaduna
</td>
<td>11,487
</td>
<td>20
</td>
<td>11,378
</td>
<td>89
</td>
</tr>
<tr>
<td>
Oyo
</td>
<td>10,328
</td>
<td>2
</td>
<td>10,124
</td>
<td>202
</td>
</tr>
<tr>
<td>
Plateau
</td>
<td>10,309
</td>
<td>27
 </td>
<td>10,207
</td>
<td>75
</td>
</tr>
<tr>
<td>
Edo
</td>
<td>7,821
</td>
<td>102
</td>
<td>7,398
</td>
<td>321
</td>
</tr>
<tr>
<td>
Ogun
</td>
<td>5,810
</td>
<td>11
</td>
<td>5,717
</td>
<td>82
</td>
</tr>
<tr>
<td>
Delta
</td>
<td>5,653
</td>
<td>371
</td>
<td>5,170
</td>
<td>112
</td>
</tr>
<tr>
<td>
Kano
</td>
<td>5,186
</td>
<td>50
</td>
<td>5,009
</td>
<td>127
</td>
</tr>
<tr>
<td>
Ondo
</td>
<td>5,173
</td>
<td>315
</td>
<td>4,749
</td>
<td>109
</td>
</tr>
<tr>
<td>
Akwa Ibom
</td>
<td>4,973
</td>
<td>22
</td>
<td>4,907
</td>
<td>44
</td>
</tr>
<tr>
<td>
Kwara
</td>
<td>4,680
</td>
<td>441
</td>
<td>4,175
</td>
<td>64
</td>
</tr>
<tr>
<td>
Osun
</td>
<td>3,311
</td>
<td>29
</td>
<td>3,190
</td>
<td>92
</td>
</tr>
<tr>
<td>
Gombe
</td>
<td>3,310
</td>
<td>6
</td>
<td>3,238
</td>
<td>66
</td>
</tr>
<tr>
<td>
Enugu
</td>
<td>2,952
</td>
<td>13
</td>
<td>2,910
</td>
<td>29
</td>
</tr>
<tr>
<td>
Anambra
</td>
<td>2,825
</td>
<td>46
</td>
<td>2,760
</td>
<td>19
</td>
</tr>
<tr>
<td>
Nasarawa
</td>
<td>2,777
 </td>
<td>393
</td>
<td>2,345
</td>
<td>39
</td>
</tr>
<tr>
<td>
Imo
</td>
<td>2,655
</td>
<td>7
</td>
<td>2,590
</td>
<td>58
</td>
</tr>
<tr>
<td>
Ekiti
</td>
<td>2,456
</td>
<td>37
</td>
<td>2,391
</td>
<td>28
</td>
</tr>
<tr>
<td>
Katsina
</td>
<td>2,418
</td>
<td>0
</td>
<td>2,381
</td>
<td>37
</td>
</tr>
<tr>
<td>
Abia
</td>
<td>2,239
</td>
<td>13
</td>
<td>2,192
</td>
<td>34
</td>
</tr>
<tr>
<td>
Benue
</td>
<td>2,129
</td>
<td>340
</td>
<td>1,764
</td>
<td>25
</td>
</tr>
<tr>
<td>
Ebonyi
</td>
<td>2,064
</td>
<td>28
</td>
<td>2,004
</td>
<td>32
</td>
</tr>
<tr>
<td>
Bauchi
</td>
<td>1,990
</td>
<td>18
</td>
<td>1,948
</td>
<td>24
</td>
</tr>
<tr>
<td>
Borno
</td>
<td>1,629
</td>
<td>5
</td>
<td>1,580
</td>
<td>44
</td>
</tr>
<tr>
<td>
Taraba
</td>
<td>1,473
</td>
<td>62
</td>
<td>1,377
</td>
<td>34
</td>
</tr>
<tr>
<td>
Bayelsa
</td>
<td>1,363
</td>
<td>10
</td>
<td>1,325
</td>
<td>28
</td>
</tr>
<tr>
<td>
Adamawa
</td>
<td>1,203
</td>
<td>68
</td>
<td>1,103
</td>
<td>32
</td>
</tr>
<tr>
<td>
Niger
 </td>
<td>1,181
</td>
<td>163
</td>
<td>998
</td>
<td>20
</td>
</tr>
<tr>
<td>
Cross River
</td>
<td>877
</td>
<td>4
</td>
<td>848
</td>
<td>25
</td>
</tr>
<tr>
<td>
Sokoto
</td>
<td>822
</td>
<td>0
</td>
<td>794
</td>
<td>28
</td>
</tr>
<tr>
<td>
Jigawa
</td>
<td>669
</td>
<td>2
</td>
<td>649
</td>
<td>18
</td>
</tr>
<tr>
<td>
Yobe
</td>
<td>638
</td>
<td>4
</td>
<td>625
</td>
<td>9
</td>
</tr>
<tr>
<td>
Kebbi
</td>
<td>480
</td>
<td>10
</td>
<td>454
</td>
<td>16
</td>
</tr>
<tr>
<td>
 Zamfara
</td>
<td>375
</td>
<td>0
</td>
<td>366
</td>
<td>9
</td>
</tr>
<tr>
<td>
Kogi
</td>
<td>5
</td>
<td>0
</td>
<td>3
</td>
<td>2
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<div class="col-xl-5">
<div class="card feed-card">
<div class="card-header">
<div class="card-box">
<h4 class="card-title">Highlights</h4>
<ul style="text-align: justify">
<li>From 23rd to 24th August 2022, 232 new confirmed cases were recorded in Nigeria</li>
<li>To date, 263322 cases have been confirmed, 257253 cases have been discharged and 3,148 deaths have been recorded in 36 states and the Federal Capital Territory</li>
<li>The 232 new cases are reported from 9 States- Lagos (117), Niger (31), Rivers (28), FCT (26), Kano (11), Kaduna (10), Plateau (4), Abia (3), Delta (2)</li>
<li>A multi-sectoral national emergency operations centre (EOC), activated at Level 2, continues to coordinate the national response activities</li>
</ul>
<a href="https://ncdc.gov.ng/diseases/sitreps/?cat=14&amp;name=An%20update%20of%20COVID-19%20outbreak%20in%20Nigeria" target="_blank"><b>Click here to read more</b></a>
</div>
</div>
</div>
<div class="card feed-card">
<div class="card-header">
<div class="card-box">
<a class="twitter-timeline" data-chrome="nofooter noborders transparent" data-height="800" data-lang="en" data-theme="light" href="https://twitter.com/NCDCgov?ref_src=twsrc%5Etfw">Tweets by NCDCgov</a>
<script async="" charset="utf-8" src="https://platform.twitter.com/widgets.js"></script>
</div>
</div>
</div>
</div>
</div>
<div class="row card-header">
<h4>Updates</h4>
</div>
<div class="row">
<div class="col-md-4 col-sm-4 col-lg-4">
<div class="card" style="height: 100px;">
<div class="card-body">
<div class="timeline-content">
<span style="display: block">
<i aria-hidden="true" class="fa fa-file-pdf" style="color:red"></i>
<a class="name" href="/media/files/F5_-_IMPLEMENTATION_GUIDELINES_Ako.pdf" target="_blank">IMPLEMENTATION GUIDELINES FOR EASING COVID-19 RESTRICTIONS </a></span>
<span class="time">April 18, 2022</span>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-sm-4 col-lg-4">
<div class="card" style="height: 100px;">
<div class="card-body">
<div class="timeline-content">
<span style="display: block">
<i aria-hidden="true" class="fa fa-file-pdf" style="color:red"></i>
<a class="name" href="/media/files/Revised_Travel_protocol_revised_2nd_April_2022.pdf" target="_blank">International Travel Protocol into Nigeria - 2nd April, 2022 </a></span>
<span class="time">Dec. 3, 2021</span>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-sm-4 col-lg-4">
<div class="card" style="height: 100px;">
<div class="card-body">
<div class="timeline-content">
<span style="display: block">
<i aria-hidden="true" class="fa fa-file-pdf" style="color:red"></i>
<a class="name" href="/media/files/PRIVATE_LABS_TRAVEL_Data.pdf" target="_blank">Private Labs Travel Data Report </a></span>
<span class="time">Nov. 11, 2021</span>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-sm-4 col-lg-4">
<div class="card" style="height: 100px;">
<div class="card-body">
<div class="timeline-content">
<span style="display: block">
<i aria-hidden="true" class="fa fa-file-pdf" style="color:red"></i>
<a class="name" href="/media/files/COVID19_private_sector__labs_MLSCN_updated_081121_Ox23ng9.docx" target="_blank">A revised version of the private sector guidance for COVID labs </a></span>
<span class="time">Nov. 11, 2021</span>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-sm-4 col-lg-4">
<div class="card" style="height: 100px;">
<div class="card-body">
<div class="timeline-content">
<span style="display: block">
<i aria-hidden="true" class="fa fa-file-pdf" style="color:red"></i>
<a class="name" href="/media/files/COVID19_private_sector__labs_MLSCN_updated_081121.docx" target="_blank">A revised version of the private sector guidance for COVID labs </a></span>
<span class="time">Nov. 11, 2021</span>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-sm-4 col-lg-4">
<div class="card" style="height: 100px;">
<div class="card-body">
<div class="timeline-content">
<span style="display: block">
<i aria-hidden="true" class="fa fa-file-pdf" style="color:red"></i>
<a class="name" href="/media/files/NITP_STATEMENT_2112021_Ako.pdf" target="_blank">STATEMENT ON THE NITP PORTAL UPGRADE </a></span>
<span class="time">Nov. 2, 2021</span>
</div>
</div>
</div>
</div>
</div>
<div class="row" style="margin-left: 10px">
<a href="/archive/" target="_blank"><b>Click here to access archive</b></a>
</div>
</div>
<div class="row">
<div class="col-md-4 col-sm-4 col-lg-4">
<div class="card">
<div class="card-body">
<iframe allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="" data-src="https://www.youtube.com/embed/G-wB_IANUzw" frameborder="0" height="315" src="" width="100%"></iframe>
</div>
</div>
</div>
<div class="col-md-4 col-sm-4 col-lg-4">
<div class="card">
<div class="card-body">

In [23]:
table = soup.find('table',{'id':'custom1'})
table

<table id="custom1">
<thead>
<tr>
<th>States Affected</th>
<th>No. of Cases (Lab Confirmed)</th>
<th>No. of Cases (on admission)</th>
<th>No. Discharged</th>
<th>No. of Deaths</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Lagos
</td>
<td>103,145
</td>
<td>2
</td>
<td>102,372
</td>
<td>771
</td>
</tr>
<tr>
<td>
FCT
</td>
<td>29,161
</td>
<td>120
</td>
<td>28,792
</td>
<td>249
</td>
</tr>
<tr>
<td>
Rivers
</td>
<td>17,755
</td>
<td>180
</td>
<td>17,420
</td>
<td>155
</td>
</tr>
<tr>
<td>
Kaduna
</td>
<td>11,487
</td>
<td>20
</td>
<td>11,378
</td>
<td>89
</td>
</tr>
<tr>
<td>
Oyo
</td>
<td>10,328
</td>
<td>2
</td>
<td>10,124
</td>
<td>202
</td>
</tr>
<tr>
<td>
Plateau
</td>
<td>10,309
</td>
<td>27
 </td>
<td>10,207
</td>
<td>75
</td>
</tr>
<tr>
<td>
Edo
</td>
<td>7,821
</td>
<td>102
</td>
<td>7,398
</td>
<td>321
</td>
</tr>
<tr>
<td>
Ogun
</td>
<td>5,810
</td>
<td>11
</td>
<td>5,717
</td>
<td>82
</td>
</tr>
<tr>
<td>
Delta
</td>
<td>5,653
</td>
<td>371
</td>
<td>5,170
</td>
<td>112
</td>
</tr>
<tr>
<td>
Kano
</td>
<td>5,186
</td>
<td>50
</td>
<td>5,009
</td>
<td>127
</td>
</tr>
<tr>
<td>
Ondo
</td>
<td>5,173
</td>
<td>315
</td>
<td>4,749
</td>
<td>109
</td>
</tr>
<tr>
<td>
Akwa Ibom
</td>
<td>4,973
</td>
<td>22
</td>
<td>4,907
</td>
<td>44
</td>
</tr>
<tr>
<td>
Kwara
</td>
<td>4,680
</td>
<td>441
</td>
<td>4,175
</td>
<td>64
</td>
</tr>
<tr>
<td>
Osun
</td>
<td>3,311
</td>
<td>29
</td>
<td>3,190
</td>
<td>92
</td>
</tr>
<tr>
<td>
Gombe
</td>
<td>3,310
</td>
<td>6
</td>
<td>3,238
</td>
<td>66
</td>
</tr>
<tr>
<td>
Enugu
</td>
<td>2,952
</td>
<td>13
</td>
<td>2,910
</td>
<td>29
</td>
</tr>
<tr>
<td>
Anambra
</td>
<td>2,825
</td>
<td>46
</td>
<td>2,760
</td>
<td>19
</td>
</tr>
<tr>
<td>
Nasarawa
</td>
<td>2,777
 </td>
<td>393
</td>
<td>2,345
</td>
<td>39
</td>
</tr>
<tr>
<td>
Imo
</td>
<td>2,655
</td>
<td>7
</td>
<td>2,590
</td>
<td>58
</td>
</tr>
<tr>
<td>
Ekiti
</td>
<td>2,456
</td>
<td>37
</td>
<td>2,391
</td>
<td>28
</td>
</tr>
<tr>
<td>
Katsina
</td>
<td>2,418
</td>
<td>0
</td>
<td>2,381
</td>
<td>37
</td>
</tr>
<tr>
<td>
Abia
</td>
<td>2,239
</td>
<td>13
</td>
<td>2,192
</td>
<td>34
</td>
</tr>
<tr>
<td>
Benue
</td>
<td>2,129
</td>
<td>340
</td>
<td>1,764
</td>
<td>25
</td>
</tr>
<tr>
<td>
Ebonyi
</td>
<td>2,064
</td>
<td>28
</td>
<td>2,004
</td>
<td>32
</td>
</tr>
<tr>
<td>
Bauchi
</td>
<td>1,990
</td>
<td>18
</td>
<td>1,948
</td>
<td>24
</td>
</tr>
<tr>
<td>
Borno
</td>
<td>1,629
</td>
<td>5
</td>
<td>1,580
</td>
<td>44
</td>
</tr>
<tr>
<td>
Taraba
</td>
<td>1,473
</td>
<td>62
</td>
<td>1,377
</td>
<td>34
</td>
</tr>
<tr>
<td>
Bayelsa
</td>
<td>1,363
</td>
<td>10
</td>
<td>1,325
</td>
<td>28
</td>
</tr>
<tr>
<td>
Adamawa
</td>
<td>1,203
</td>
<td>68
</td>
<td>1,103
</td>
<td>32
</td>
</tr>
<tr>
<td>
Niger
 </td>
<td>1,181
</td>
<td>163
</td>
<td>998
</td>
<td>20
</td>
</tr>
<tr>
<td>
Cross River
</td>
<td>877
</td>
<td>4
</td>
<td>848
</td>
<td>25
</td>
</tr>
<tr>
<td>
Sokoto
</td>
<td>822
</td>
<td>0
</td>
<td>794
</td>
<td>28
</td>
</tr>
<tr>
<td>
Jigawa
</td>
<td>669
</td>
<td>2
</td>
<td>649
</td>
<td>18
</td>
</tr>
<tr>
<td>
Yobe
</td>
<td>638
</td>
<td>4
</td>
<td>625
</td>
<td>9
</td>
</tr>
<tr>
<td>
Kebbi
</td>
<td>480
</td>
<td>10
</td>
<td>454
</td>
<td>16
</td>
</tr>
<tr>
<td>
 Zamfara
</td>
<td>375
</td>
<td>0
</td>
<td>366
</td>
<td>9
</td>
</tr>
<tr>
<td>
Kogi
</td>
<td>5
</td>
<td>0
</td>
<td>3
</td>
<td>2
</td>
</tr>
</tbody>
</table>

In [24]:
headers = []
for i in table.find_all('th'):
    title = i.text
    headers.append(title)

In [25]:
df = pd.DataFrame(columns = headers)

In [26]:
df

Empty DataFrame
Columns: [States Affected, No. of Cases (Lab Confirmed), No. of Cases (on admission), No. Discharged, No. of Deaths]
Index: []

In [27]:
for row in table.find_all('tr')[1:]:
    data = row.find_all('td')
    row_data = [td.text.strip() for td in data]
    length = len(df)
    df.loc[length] = row_data

In [28]:
df

,States Affected,No. of Cases (Lab Confirmed),No. of Cases (on admission),No. Discharged,No. of Deaths
0,Lagos,"103,145",2,"102,372",771
1,FCT,"29,161",120,"28,792",249
2,Rivers,"17,755",180,"17,420",155
3,Kaduna,"11,487",20,"11,378",89
4,Oyo,"10,328",2,"10,124",202
5,Plateau,"10,309",27,"10,207",75
6,Edo,"7,821",102,"7,398",321
7,Ogun,"5,810",11,"5,717",82
8,Delta,"5,653",371,"5,170",112
9,Kano,"5,186",50,"5,009",127
10,Ondo,"5,173",315,"4,749",109
11,Akwa Ibom,"4,973",22,"4,907",44
12,Kwara,"4,680",441,"4,175",64
13,Osun,"3,311",29,"3,190",92
14,Gombe,"3,310",6,"3,238",66
15,Enugu,"2,952",13,"2,910",29
16,Anambra,"2,825",46,"2,760",19
17,Nasarawa,"2,777",393,"2,345",39
18,Imo,"2,655",7,"2,590",58
19,Ekiti,"2,456",37,"2,391",28
20,Katsina,"2,418",0,"2,381",37
21,Abia,"2,239",13,"2,192",34
22,Benue,"2,129",340,"1,764",25
23,Ebonyi,"2,064",28,"2,004",32
24,Bauchi,"1,990",18,"1,948",24
25,Borno,"1,629",5,"1,580",44
26,Taraba,"1,473",62,"1,377",34
27,Bayelsa,"1,363",10,"1,325",28
28,Adamawa,"1,203",68,"1,103",32
29,Niger,"1,181",163,998,20
30,Cross River,877,4,848,25
31,Sokoto,822,0,794,28
32,Jigawa,669,2,649,18
33,Yobe,638,4,625,9
34,Kebbi,480,10,454,16
35,Zamfara,375,0,366,9
36,Kogi,5,0,3,2

### B - John Hopkins Data Repository
Here you will obtain data from the John Hopkins repository. Your task here involves saving the data from the GitHub repo link to DataFrame for further analysis. Find the links below. 
* Global Daily Confirmed Cases - Click [Here](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv)
* Global Daily Recovered Cases - Click [Here](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv)
* Global Daily Death Cases - Click [Here](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv)

## Dataset of global daily confirmed cases

In [29]:
PATH = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv'

In [30]:
df_confirmed = pd.read_csv(PATH)

In [31]:
df_confirmed

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,8/21/22,8/22/22,8/23/22,8/24/22,8/25/22,8/26/22,8/27/22,8/28/22,8/29/22,8/30/22
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,190643,191040,191247,191585,191967,191967,191967,192463,192906,193004
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,326077,326181,326787,327232,327607,327961,328299,328515,328571,329017
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,269805,269894,269971,270043,270097,270145,270175,270194,270235,270272
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,45975,45975,45975,46027,46027,46027,46027,46027,46027,46027
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,102636,102636,102636,102636,102636,102636,102636,102636,102636,102636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,697447,698384,698384,698384,698384,698384,698384,698384,698384,701739
281,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,535,535,535,535,535,535,535,535,535,535
282,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,11915,11915,11917,11919,11922,11922,11925,11925,11925,11926
283,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,332264,332527,332527,332648,332710,332710,332710,332710,332822,332822
284,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,256624,256628,256628,256628,256675,256682,256682,256699,256704,256708

## Dataset of global daily recovered cases

In [32]:
PATHS_R = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv'

In [33]:
df_recover = pd.read_csv(PATHS_R)

In [34]:
df_recover.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,8/21/22,8/22/22,8/23/22,8/24/22,8/25/22,8/26/22,8/27/22,8/28/22,8/29/22,8/30/22
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Dataset of global daily death cases

In [35]:
PATH_D = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv'

In [36]:
df_death = pd.read_csv(PATH_D)

In [37]:
df_death

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,8/21/22,8/22/22,8/23/22,8/24/22,8/25/22,8/26/22,8/27/22,8/28/22,8/29/22,8/30/22
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,7762,7767,7768,7769,7771,7771,7771,7777,7777,7777
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,3576,3576,3577,3578,3579,3580,3581,3581,3581,3582
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,6878,6878,6878,6878,6878,6878,6878,6878,6878,6878
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,154,154,154,154,154,154,154,154,154,154
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,1917,1917,1917,1917,1917,1917,1917,1917,1917,1917
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,5691,5694,5694,5694,5694,5694,5694,5694,5694,5700
281,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
282,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,2154,2154,2154,2155,2155,2155,2155,2155,2155,2155
283,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,4016,4016,4016,4016,4016,4016,4016,4016,4016,4016
284,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,5592,5592,5592,5592,5593,5593,5593,5593,5593,5593

## C - External Data 
* Save the external data to a DataFrame
* External Data includes but not limited to: `covid_external.csv`, `Budget data.csv`, `RealGDP.csv`

In [42]:
df_budget = pd.read_csv('Budget_data2.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'Budget_data2.csv'

In [43]:
df_covid_external = pd.read_csv('covid_external.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'covid_external.csv'

In [ ]:
df_real_gdp = pd.read_csv('RealGDP.csv')

### Task 2 - View the data
Obtain basic information about the data using the `head()` and `info()` method.

In [ ]:
df_budget.head()

In [ ]:
df_covid_external.head()

In [ ]:
df_real_gdp

### Task 3 - Data Cleaning and Preparation
From the information obtained above, I fixed the data format. 
<br>
Examples: 
* Convert to appropriate data type.
* Rename the columns of the scraped data.
* Remove comma(,) in numerical data
* Extract daily data for Nigeria from the Global daily cases data

### Cleaning the Scraped Data

In [ ]:
df.dtypes

In [ ]:
df.rename(columns = {'States Affected':'states','No. of Cases (Lab Confirmed)':'Confirmed Cases','No. of Cases (on admission)':'Admitted Cases','No. Discharged':'Discharged Cases','No. of Deaths':'Death Cases'},inplace = True)

In [ ]:
df

In [ ]:
df = df.replace(',','', regex=True)

In [ ]:
df.head()

### Cleaning John Hopkins data

In [ ]:
df_confirmed.drop(['Province/State','Lat','Long'], axis = 1,inplace = True)

In [ ]:
df_confirmed.head()

In [ ]:
df_recover.drop(['Province/State','Lat','Long'], axis = 1,inplace = True)

In [ ]:
df_recover.head()

In [ ]:
df_death.drop(['Province/State','Lat','Long'], axis = 1,inplace = True)

In [ ]:
df_death.head()


### Extracting Daily Data from the Global Daily Cases

* #### Nigeria Daily Data for Confirmed Cases

In [ ]:
nigeria_confirmed = df_confirmed[df_confirmed["Country/Region"] == "Nigeria"]

In [ ]:
nigeria_confirmed

* #### Nigeria Daily Data for Recovered Cases

In [ ]:
nigeria_recovered = df_recover[df_recover["Country/Region"] == "Nigeria"]

In [ ]:
nigeria_recovered

* #### Nigeria Daily Data for Death Cases

In [ ]:
nigeria_death_cases = df_death[df_death["Country/Region"] == "Nigeria"]

In [ ]:
nigeria_death_cases

### A Pandas DataFrame for Daily Confirmed Cases in Nigeria. Columns are Date and Cases

In [ ]:
columns = nigeria_confirmed.iloc[:, 4:]

df_nigeria_confirmed = nigeria_confirmed.melt(value_vars=columns, var_name="Date", value_name="Cases")

In [ ]:
df_nigeria_confirmed.head()

* #### Cleaning the data by making date a datetime datatype.

In [ ]:
df_nigeria_confirmed["Date"] = df_nigeria_confirmed["Date"].apply(pd.to_datetime, errors='coerce')

### A Pandas DataFrame for Daily Recovered Cases in Nigeria. Columns are Date and Cases

In [ ]:
columns = nigeria_recovered.iloc[:, 4:]

df_nigeria_recovered = nigeria_recovered.melt(value_vars=columns, var_name="Date", value_name="Cases")

In [ ]:
df_nigeria_recovered.head()

* #### Cleaning the data by making date a datetime datatype.

In [ ]:
df_nigeria_recovered["Date"] = df_nigeria_recovered["Date"].apply(pd.to_datetime, errors='coerce')

### A Pandas DataFrame for Daily Death Cases in Nigeria. Columns are Date and Cases

In [ ]:
columns = nigeria_death_cases.iloc[:, 4:]

df_nigeria_death_cases = nigeria_death_cases.melt(value_vars=columns, var_name="Date", value_name="Cases")

In [ ]:
df_nigeria_death_cases.head()

* #### Cleaning the data by making date a datetime datatype.

In [ ]:
df_nigeria_death_cases["Date"] = df_nigeria_death_cases["Date"].apply(pd.to_datetime, errors='coerce')

## Task 4 - Data Visualization

### TODO A - Generate a plot that shows the Top 10 states in terms of Confirmed Covid cases by Laboratory test

In [ ]:
df['Confirmed Cases'] = pd.to_numeric(df['Confirmed Cases'])

In [ ]:
df_ncdc_confirm = df.sort_values(by = ['Confirmed Cases'],ascending=False).head(10)

In [ ]:
df_ncdc_confirm

In [ ]:
plt.figure(figsize=(12,5))
sns.barplot(x = 'states',y = 'Confirmed Cases',data = df_ncdc_confirm).set_title('Top 10 States in terms of Confirmed Cases',fontsize = 20)

#### Summary: Lagos State tops in terms of Confirmed Cases with FCT(Abuja) second and Rivers State is third.

### TODO B - Generate a plot that shows the Top 10 states in terms of Discharged Covid cases. Hint - Sort the values

In [ ]:
df['Discharged Cases'] = pd.to_numeric(df['Discharged Cases'])

In [ ]:
df_ncdc_discharged = df.sort_values(by = ['Discharged Cases'],ascending=False).head(11)

In [ ]:
df_ncdc_discharged

In [ ]:
plt.figure(figsize=(12,5))
sns.barplot(x = 'states',y = 'Discharged Cases',data = df_ncdc_discharged).set_title('Top 10 States in terms of Discharged Cases',fontsize = 20)

#### Summary:  Lagos State tops in terms of Discharged Cases with FCT(Abuja) second and Rivers State is third.

### TODO C - Plot the top 10 Death cases

In [ ]:
df['Death Cases'] = pd.to_numeric(df['Death Cases'])

In [ ]:
df_ncdc_death = df.sort_values(by = ['Death Cases'],ascending=False).head(11)

In [ ]:
df_ncdc_death

In [ ]:
plt.figure(figsize=(12,5))
sns.barplot(x = 'states',y = 'Death Cases',data = df_ncdc_death).set_title('Top 10 States in terms of Death Cases',fontsize = 20)

#### Summary:  Lagos State tops in terms of Death Cases with Edo State second and FCT is third.

### TODO D - Generate a line plot for the total daily confirmed, recovered and death cases in Nigeria

In [ ]:
sns.set(rc={'figure.figsize':(12,10)})

sns.lineplot(df_nigeria_confirmed.Date, df_nigeria_confirmed.Cases,linewidth=3, label="Daily Confirmed Cases in Nigeria", color="r", markers="o")

sns.lineplot(df_nigeria_recovered.Date, df_nigeria_recovered.Cases,linewidth=3, label="Daily Recovered Cases in Nigeria", color="b")

sns.lineplot(df_nigeria_death_cases.Date, df_nigeria_death_cases.Cases,linewidth=3, label="Daily Death Cases in Nigeria", color="g")

#Title, labels and legend
plt.xlabel("Dates", fontsize=20)
plt.ylabel("Numbers of Cases", fontsize=20)
plt.xticks(rotation=90)
plt.title ("Total Daily Confirmed, Recovered and Death Cases in Nigeria", fontsize=30)
plt.show()

### TODO E - 
* Determine the daily infection rate, you can use the Pandas `diff` method to find the derivate of the total cases.
* Generate a line plot for the above

In [ ]:
df_nigeria_daily_infection_rate = df_nigeria_confirmed.Cases.diff()
plt.figure(figsize=(15,5))
sns.lineplot(df_nigeria_confirmed.Date, df_nigeria_daily_infection_rate).set_title("Daily Infection Rates in Nigeria", fontdict = { 'fontsize': 20});

### TODO F - 
* Calculate maximum infection rate for a day (Number of new cases)

In [ ]:
df_nigeria_confirmed["Daily Infection Rate"] = df_nigeria_confirmed["Cases"].diff()
max_infection = df_nigeria_confirmed["Daily Infection Rate"].max()

In [ ]:
max_infection

### TODO G - Determine the relationship between the external dataset and the NCDC COVID-19 dataset. 
Here you will generate a line plot of top 10 confirmed cases and the overall community vulnerability index on the same axis. From the graph, explain your observation.

In [39]:
df2 = pd.merge(df,df_covid_external,on = 'states')

NameError: name 'df_covid_external' is not defined

In [40]:
df2

NameError: name 'df2' is not defined

In [41]:
df_confirmed_vulnerabilty = df2.nlargest(10,['Confirmed Cases','Overall CCVI Index'])

NameError: name 'df2' is not defined

In [ ]:
df_confirmed_vulnerabilty

In [ ]:
x=df_confirmed_vulnerabilty['states']
y1 = df_confirmed_vulnerabilty['Confirmed Cases']
y2 = df_confirmed_vulnerabilty['Overall CCVI Index']
fig, ax1 = plt.subplots(figsize = (12,7))
plt.title('The Top 10 Confirmed Cases and the Overall CCVI Index',fontsize=25)
ax1.set_xlabel('States',fontsize=20)
ax1.set_ylabel('Top 10 Confirmed Cases',color = 'r',fontsize=20)
ax2 = ax1.twinx()
ax2.set_ylabel('Overall CCVI Index',color = 'b',fontsize=20)
curve1 = ax1.plot(x, y1, label = 'Confirmed Cases', color = 'r')
curve2 = ax1.plot(x, y2, label='Overall CCVI Index', color = 'b')
plt.plot()
plt.show()

### TODO H - Determine the relationship between the external dataset and the NCDC COVID-19 dataset. 
* Here I generated a regression plot between two variables to visualize the linear relationships - Confirmed Cases and Population Density.

In [ ]:
b = df_confirmed_vulnerabilty['Confirmed Cases']
c = df_confirmed_vulnerabilty['Population Density']
plt.subplots(figsize = (12,5))
plt.title('The Top 10 Confirmed Cases and the Overall CCVI Index',fontsize=25)
plt.xlabel('States',fontsize=20)
plt.ylabel('Population Density',fontsize=20)
sns.regplot(x=b,y= c, data= df_confirmed_vulnerabilty)
plt.show()

## TODO L -
Determine the effect of the Pandemic on the economy. To do this, you will compare the Real GDP value Pre-COVID-19 with Real GDP in 2020

In [ ]:

df_nigeria_real_gdp = df_real_gdp.melt(id_vars= 'Year',value_vars= ['Q1','Q2','Q3','Q4'],var_name='Quarters',value_name = 'Quarter_value')
df_nigeria_real_gdp

In [ ]:
d=df_nigeria_real_gdp['Year']
e= df_nigeria_real_gdp['Quarter_value']
plt.subplots(3,3 figsize=(12,5))
plt.bar(d,e)
plt.axhline(1.58e7,c='r',linewidth=2)
plt.title('Years and their GDP Quarter values',fontsize=25)
plt.xlabel('Year',fontsize=20)
plt.ylabel('Quarter value',fontsize=20)
plt.show()

#### Summary: The red horizontal line is the quarter value of 2020 Q2 which is the lowest GDP of the country due to the effect of Covid-19.